# Generated by Django 5.0.3 on 2024-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patients_medicalrecords_predictionresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='chest_pain',
            field=models.IntegerField(choices=[(0, 'Typical Angina'), (1, 'Atypical Angina'), (2, 'Non-anginal Pain'), (3, 'Asymptomatic')]),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='exercise_angina',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='fasting_bs',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')]),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='resting_ecg',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Having ST-T wave abnormality'), (2, 'Probable or definite left ventricular hypertrophy')]),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='slope',
            field=models.IntegerField(choices=[(0, 'Upsloping'), (1, 'Flat'), (2, 'Downsloping')]),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='thal',
            field=models.IntegerField(choices=[(3, 'Normal'), (6, 'Fixed defect'), (7, 'Reversible defect')]),
        ),
    ]
